# Site settings
title: "Saman Darougheh"
description: "Researcher on macroeconomics and labor markets"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings

resume_name:                    "Saman Darougheh"








# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      pdf: true